import { createServerClient } from '@supabase/ssr'
import { NextResponse, type NextRequest } from 'next/server'

export async function proxy(request: NextRequest) {
  let supabaseResponse = NextResponse.next({
    request,
  })

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll()
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) => {
            request.cookies.set(name, value)
          })
          supabaseResponse = NextResponse.next({
            request,
          })
          cookiesToSet.forEach(({ name, value, options }) => {
            supabaseResponse.cookies.set(name, value, options)
          })
        },
      },
    },
  )

  // Refresh session if expired - this will automatically
  // refresh the token if needed
  const {
    data: { user },
  } = await supabase.auth.getUser()

  // Define route types
  const pathname = request.nextUrl.pathname
  const isLoginPage = pathname === '/login'
  const isAuthRoute = pathname.startsWith('/auth')
  // Public routes: the marketing landing (front door). Everything else requires auth.
  const publicRoutes = ['/']
  // Brand/metadata assets generated by Next file conventions: social crawlers
  // fetch these unauthenticated. They carry no user or registry data.
  const isMetadataAsset =
    pathname === '/manifest.webmanifest' ||
    pathname.startsWith('/opengraph-image') ||
    pathname.startsWith('/twitter-image') ||
    pathname.startsWith('/icon') ||
    pathname.startsWith('/apple-icon')
  // Shared design lightpapers: access control is the unguessable slug
  // itself, resolved by an anon-granted SECURITY DEFINER function that
  // returns a curated payload (no table access). A revoked slug 404s.
  const isShareRoute = pathname.startsWith('/share/')
  // TEMPORARY (dither-kit pilot): the design-labs comparison page. Static
  // sample data, no user or registry data. Dev-only twice over — this check,
  // and the page itself 404s outside dev. Delete both with the pilot.
  const isDevLabsRoute =
    process.env.NODE_ENV !== 'production' && pathname.startsWith('/labs')
  const isPublicRoute =
    isLoginPage ||
    isAuthRoute ||
    isMetadataAsset ||
    isShareRoute ||
    isDevLabsRoute ||
    publicRoutes.includes(pathname)
  const isProtectedRoute = !isPublicRoute

  // Redirect logic
  if (!user && isProtectedRoute) {
    // Not authenticated - redirect to login
    const url = request.nextUrl.clone()
    url.pathname = '/login'
    return NextResponse.redirect(url)
  }

  if (user && isLoginPage) {
    // Already authenticated - redirect to dashboard
    const url = request.nextUrl.clone()
    url.pathname = '/dashboard'
    return NextResponse.redirect(url)
  }

  return supabaseResponse
}

export const config = {
  matcher: [
    /*
     * Match all request paths except for:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - public files (images, SVGs, etc.)
     */
    '/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)',
  ],
}
